Generate gamerecord list
Anmint/Ktuarto pull request #21
Opened 2022-01-30 08:50 UTC by Anmint

棋譜データを出力できるように、Gamerecordリストを生成した。また、CUI上で確認できるためのprintメソッドも実装。

2022-02-17 04:09 UTC, unigiriunini requested changes
レビューが遅くなり申し訳ありません！1点変更をお願いしたい箇所があるため、ご確認よろしくお願いします。

2022-02-17 04:09 UTC, unigiriunini commented on ktuarto/utils/gamemain.py
> +            self.gamerecord.append((self.choicepiece.toNumList(), (self.left, self.top), self.call))
ここは `self.gamerecord` に格納する値として `self.choicepiece.toNumList()` ではなく `self.choicepiece` を指定して頂きたいです。

理由としては `toNumList()` の結果は `array([2, 1, 1, 1])` のようなリストの形となるのですが、この状態だと配列のどの数字が駒のどの特徴(色、高さなど)を示しているかの情報が失われるためです。
今後Piece classの仕様が変更された時にそれへの対応を忘れてバグらないようにしたいため、ここは `self.choicepiece` (Piece classのオブジェクト)をそのままappendして頂きたいです。

2022-02-17 04:09 UTC, unigiriunini commented on ktuarto/utils/util.py
> +            print("".join(map(str, hand[0].tolist())) + "(" + chr(hand[1][1] + 97) + str(4 - hand[1][0]) + ")" + quarto)
もしレビューに書いたように `self.choicepiece` をgamerecordに格納した場合、ここの `hand[0].tolist()` は `hand[0].toNumList().tolist()` に変更する必要があります。

2022-02-17 04:15 UTC, unigiriunini commented on ktuarto/utils/util.py
> +            print("".join(map(str, hand[0].tolist())) + "(" + chr(hand[1][1] + 97) + str(4 - hand[1][0]) + ")" + quarto)
これは必須変更ではありませんが、 `.toNumList().tolist()` のところを `toDict()` にすると `{'color': 'dark', 'shape': 'square', 'top': 'solid', 'height': 'short'}` のように人間フレンドリーな見た目になるので読みやすくなりそうです。

2022-02-21 12:18 UTC, Anmint commented
ご指摘感謝！指摘どおり直しましたー

2022-02-21 12:19 UTC, unigiriunini approved these changes
ありがとうございます！

2022-02-21 12:32 UTC, merged